services:
  db:
    image: postgres:17
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - backend
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped

  api-server:
    build: ./backend
    container_name: api-server
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - backend
    restart: unless-stopped

volumes:
  db-data:


networks:
  backend:
    driver: bridge
