services:
  postgres-db:
    image: postgres:17
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - backend
    volumes:
      - postgres-db-data:/var/lib/postgresql/data
    restart: unless-stopped

  migrator:
    image: migrate/migrate
    container_name: migrator
    networks:
      - backend
    volumes:
      - ./migrations:/migrations
    entrypoint: [ "migrate" ]
    depends_on:
      - postgres-db

  api-server:
    build: ./backend
    container_name: api-server
    env_file:
      - .env
    depends_on:
      - postgres-db
    networks:
      - backend
    restart: unless-stopped

volumes:
  postgres-db-data:


networks:
  backend:
    driver: bridge
